kind: pipeline
name: audit

steps:
- name: audit
  image: baiduxlab/sgx-rust:1604-1.1.1
  commands:
  - . /opt/sgxsdk/environment
  - . /root/.cargo/env
  - rustup default 1.36.0
  - cargo install cargo-audit
  - cd dumb-all && cargo audit --ignore RUSTSEC-2016-0005

---
kind: pipeline
name: world-xargo-1604-release

steps:
- name: release-compile
  image: baiduxlab/sgx-rust:1604-1.1.1
  commands:
  - . /opt/sgxsdk/environment
  - . /root/.cargo/env
  - cd dumb-all && RUST_TARGET_PATH=`pwd` xargo build --target x86_64-unknown-linux-sgx --release

---

kind: pipeline
name: world-xargo-1604-debug

steps:
- name: debug-compile
  image: baiduxlab/sgx-rust:1604-1.1.1
  commands:
  - . /opt/sgxsdk/environment
  - . /root/.cargo/env
  - cd dumb-all && RUST_TARGET_PATH=`pwd` xargo build --target x86_64-unknown-linux-sgx

---

kind: pipeline
name: world-xargo-1804-release

steps:
- name: release-compile
  image: baiduxlab/sgx-rust:1804-1.1.1
  commands:
  - . /opt/sgxsdk/environment
  - . /root/.cargo/env
  - cd dumb-all && RUST_TARGET_PATH=`pwd` xargo build --target x86_64-unknown-linux-sgx --release

---

kind: pipeline
name: world-xargo-1804-debug

steps:
- name: debug-compile
  image: baiduxlab/sgx-rust:1804-1.1.1
  commands:
  - . /opt/sgxsdk/environment
  - . /root/.cargo/env
  - cd dumb-all && RUST_TARGET_PATH=`pwd` xargo build --target x86_64-unknown-linux-sgx

---

kind: pipeline
name: world-1604-release

steps:
- name: release-compile
  image: baiduxlab/sgx-rust:1604-1.1.1
  commands:
  - . /opt/sgxsdk/environment
  - . /root/.cargo/env
  - cd dumb-all && cargo build --release

---

kind: pipeline
name: world-1604-hw-debug

steps:
- name: debug-compile
  image: baiduxlab/sgx-rust:1604-1.1.1
  commands:
  - . /opt/sgxsdk/environment
  - . /root/.cargo/env
  - cd dumb-all && cargo build

---

kind: pipeline
name: world-1804-release

steps:
- name: release-compile
  image: baiduxlab/sgx-rust:1804-1.1.1
  commands:
  - . /opt/sgxsdk/environment
  - . /root/.cargo/env
  - cd dumb-all && cargo build --release

---

kind: pipeline
name: world-1804-debug

steps:
- name: debug-compile
  image: baiduxlab/sgx-rust:1804-1.1.1
  commands:
  - . /opt/sgxsdk/environment
  - . /root/.cargo/env
  - cd dumb-all && cargo build
